import { DownloadOutlined, ExportOutlined, FileExcelOutlined } from '@ant-design/icons';
import billService from '@/services/Bills';
import centersStore from '@stores/CentersStore';
import userStore from '@stores/UserStore';
import { Button, Checkbox, DatePicker, Modal, Select, Spin, Tag, Tooltip, message } from 'antd';
import dayjs from 'dayjs';
import React, { useEffect, useMemo, useState } from 'react';
import { useStore } from 'zustand';
import * as XLSX from 'xlsx';

const { RangePicker } = DatePicker;

// All available export fields with their metadata
const EXPORT_FIELDS = [
  { key: 'invoiceNo', label: 'Invoice Number', group: 'Bill' },
  { key: 'financial_year', label: 'Financial Year', group: 'Bill' },
  { key: 'generated_on', label: 'Generated Date', group: 'Bill' },
  { key: 'payment_date', label: 'Payment Date', group: 'Bill' },
  { key: 'status', label: 'Status', group: 'Bill' },
  { key: 'subject', label: 'Subject', group: 'Bill' },
  { key: 'payment_method', label: 'Payment Method', group: 'Bill' },
  { key: 'items', label: 'Items', group: 'Bill' },
  { key: 'subtotal', label: 'Subtotal', group: 'Amount' },
  { key: 'total_discount', label: 'Total Discount', group: 'Amount' },
  { key: 'total_tax', label: 'Total Tax', group: 'Amount' },
  { key: 'total', label: 'Total Amount', group: 'Amount' },
  { key: 'finalTotal', label: 'Final Total (after wallet)', group: 'Amount' },
  { key: 'walletAmountDeducted', label: 'Wallet Deduction', group: 'Amount' },
  { key: 'student_name', label: 'Student Name', group: 'Student' },
  { key: 'student_email', label: 'Student Email', group: 'Student' },
  { key: 'student_phone', label: 'Student Phone', group: 'Student' },
  { key: 'admission_number', label: 'Admission No.', group: 'Student' },
  { key: 'center_name', label: 'Center', group: 'Center' },
  { key: 'generated_by_name', label: 'Generated By', group: 'Staff' },
  { key: 'remarks', label: 'Remarks', group: 'Bill' },
];

// Group fields by category for display
const FIELD_GROUPS = ['Bill', 'Amount', 'Student', 'Center', 'Staff'];

// Default selected fields
const DEFAULT_FIELDS = [
  'invoiceNo', 'generated_on', 'status', 'subject', 'student_name',
  'total', 'payment_method', 'payment_date', 'center_name'
];

/**
 * Flatten a populated bill document into an export-ready row.
 */
function flattenBill(bill, selectedFields) {
  const row = {};
  const fieldSet = new Set(selectedFields);

  if (fieldSet.has('invoiceNo')) {
    const prefix = bill.center_initial || bill.center_id?.center_initial || '';
    row['Invoice Number'] = bill.invoiceNo ? `${prefix}${bill.invoiceNo}` : 'Draft';
  }
  if (fieldSet.has('financial_year')) {
    row['Financial Year'] = bill.financial_year || '';
  }
  if (fieldSet.has('generated_on')) {
    row['Generated Date'] = bill.generated_on ? dayjs(bill.generated_on).format('DD/MM/YYYY') : '';
  }
  if (fieldSet.has('payment_date')) {
    row['Payment Date'] = bill.payment_date ? dayjs(bill.payment_date).format('DD/MM/YYYY') : '';
  }
  if (fieldSet.has('status')) {
    row['Status'] = (bill.status || '').charAt(0).toUpperCase() + (bill.status || '').slice(1);
  }
  if (fieldSet.has('subject')) {
    row['Subject'] = (bill.subject || '').charAt(0).toUpperCase() + (bill.subject || '').slice(1);
  }
  if (fieldSet.has('payment_method')) {
    row['Payment Method'] = (bill.payment_method || '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  }
  if (fieldSet.has('items')) {
    row['Items'] = (bill.items || []).map(i => `${i.name}${i.qty > 1 ? ` x${i.qty}` : ''}`).join(', ');
  }
  if (fieldSet.has('subtotal')) {
    row['Subtotal'] = bill.subtotal ?? '';
  }
  if (fieldSet.has('total_discount')) {
    row['Total Discount'] = bill.total_discount ?? '';
  }
  if (fieldSet.has('total_tax')) {
    row['Total Tax'] = bill.total_tax ?? '';
  }
  if (fieldSet.has('total')) {
    row['Total Amount'] = bill.total ?? '';
  }
  if (fieldSet.has('finalTotal')) {
    row['Final Total'] = bill.finalTotal ?? '';
  }
  if (fieldSet.has('walletAmountDeducted')) {
    row['Wallet Deduction'] = bill.walletAmountDeducted ?? '';
  }
  if (fieldSet.has('student_name')) {
    row['Student Name'] = bill.generated_for?.username || '';
  }
  if (fieldSet.has('student_email')) {
    row['Student Email'] = bill.generated_for?.email || '';
  }
  if (fieldSet.has('student_phone')) {
    row['Student Phone'] = bill.generated_for?.phone || '';
  }
  if (fieldSet.has('admission_number')) {
    row['Admission No.'] = bill.generated_for?.details_id?.admissionNumber || '';
  }
  if (fieldSet.has('center_name')) {
    row['Center'] = bill.center_id?.center_name || '';
  }
  if (fieldSet.has('generated_by_name')) {
    row['Generated By'] = bill.generated_by?.username || '';
  }
  if (fieldSet.has('remarks')) {
    row['Remarks'] = bill.remarks || '';
  }

  return row;
}

function ExportBillsModal() {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [dateRange, setDateRange] = useState(null);
  const [selectedCenters, setSelectedCenters] = useState(['all']);
  const [selectedFields, setSelectedFields] = useState(DEFAULT_FIELDS);
  const [statusFilter, setStatusFilter] = useState('all');
  const [subjectFilter, setSubjectFilter] = useState('all');
  const [exportFormat, setExportFormat] = useState('xlsx');

  const { centers, getCenters } = useStore(centersStore);
  const { user } = useStore(userStore);

  useEffect(() => {
    if (open && centers.length === 0) {
      getCenters(0);
    }
  }, [open]);

  const centerOptions = useMemo(() => {
    const opts = [{ label: 'All Centers', value: 'all' }];
    centers.forEach(c => {
      opts.push({ label: c.center_name, value: c._id });
    });
    return opts;
  }, [centers]);

  const handleCenterChange = (values) => {
    // If "all" is selected, deselect everything else
    if (values.includes('all') && !selectedCenters.includes('all')) {
      setSelectedCenters(['all']);
    } else if (selectedCenters.includes('all') && values.length > 1) {
      // If something else is selected while "all" is active, remove "all"
      setSelectedCenters(values.filter(v => v !== 'all'));
    } else {
      setSelectedCenters(values.length === 0 ? ['all'] : values);
    }
  };

  const handleSelectAllFields = () => {
    setSelectedFields(EXPORT_FIELDS.map(f => f.key));
  };

  const handleDeselectAllFields = () => {
    setSelectedFields([]);
  };

  const handleFieldToggle = (key) => {
    setSelectedFields(prev =>
      prev.includes(key)
        ? prev.filter(k => k !== key)
        : [...prev, key]
    );
  };

  const handleExport = async () => {
    if (!dateRange || !dateRange[0] || !dateRange[1]) {
      message.warning('Please select a date range');
      return;
    }
    if (selectedFields.length === 0) {
      message.warning('Please select at least one field to export');
      return;
    }

    setLoading(true);
    try {
      const response = await billService.exportBills({
        dateRange: {
          from: dateRange[0].toISOString(),
          to: dateRange[1].toISOString(),
        },
        centerIds: selectedCenters,
        selectedFields,
        status: statusFilter,
        subject: subjectFilter,
      });

      const bills = response?.bills || [];

      if (bills.length === 0) {
        message.info('No bills found for the selected filters');
        setLoading(false);
        return;
      }

      // Flatten bills into export rows
      const rows = bills.map(bill => flattenBill(bill, selectedFields));

      // Generate file
      const worksheet = XLSX.utils.json_to_sheet(rows);

      // Auto-size columns
      const colWidths = Object.keys(rows[0] || {}).map(key => ({
        wch: Math.max(key.length, ...rows.map(r => String(r[key] || '').length).slice(0, 100)) + 2
      }));
      worksheet['!cols'] = colWidths;

      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, 'Bills');

      const fromDate = dateRange[0].format('DD-MMM-YYYY');
      const toDate = dateRange[1].format('DD-MMM-YYYY');
      const fileName = `Bills_Export_${fromDate}_to_${toDate}`;

      if (exportFormat === 'xlsx') {
        XLSX.writeFile(workbook, `${fileName}.xlsx`);
      } else {
        XLSX.writeFile(workbook, `${fileName}.csv`, { bookType: 'csv' });
      }

      message.success(`Exported ${bills.length} bills successfully`);
    } catch (error) {
      console.error('Export failed:', error);
      message.error('Export failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setDateRange(null);
    setSelectedCenters(['all']);
    setSelectedFields(DEFAULT_FIELDS);
    setStatusFilter('all');
    setSubjectFilter('all');
    setExportFormat('xlsx');
  };

  return (
    <>
      <Tooltip title="Export Bills">
        <Button
          icon={<ExportOutlined />}
          onClick={() => setOpen(true)}
          className="rounded-full"
          variant="filled"
          color="blue"
        >
          Export
        </Button>
      </Tooltip>

      <Modal
        title={
          <div className="flex items-center gap-2">
            <FileExcelOutlined className="text-green-600" />
            <span>Export Bills</span>
          </div>
        }
        open={open}
        onCancel={() => setOpen(false)}
        width={720}
        footer={[
          <Button key="reset" onClick={handleReset}>
            Reset
          </Button>,
          <Button key="cancel" onClick={() => setOpen(false)}>
            Cancel
          </Button>,
          <Button
            key="export"
            type="primary"
            icon={<DownloadOutlined />}
            onClick={handleExport}
            loading={loading}
            disabled={!dateRange || selectedFields.length === 0}
          >
            {loading ? 'Exporting...' : 'Export'}
          </Button>,
        ]}
      >
        <div className="flex flex-col gap-5 py-4">

          {/* Date Range */}
          <div>
            <label className="block text-sm font-medium text-gray-600 mb-1.5">Date Range <span className="text-red-500">*</span></label>
            <RangePicker
              value={dateRange}
              onChange={setDateRange}
              className="w-full"
              size="large"
              format="DD/MM/YYYY"
              presets={[
                { label: 'This Month', value: [dayjs().startOf('month'), dayjs().endOf('month')] },
                { label: 'Last Month', value: [dayjs().subtract(1, 'month').startOf('month'), dayjs().subtract(1, 'month').endOf('month')] },
                { label: 'Last 3 Months', value: [dayjs().subtract(3, 'month').startOf('month'), dayjs()] },
                { label: 'This Year', value: [dayjs().startOf('year'), dayjs()] },
                { label: 'Last Year', value: [dayjs().subtract(1, 'year').startOf('year'), dayjs().subtract(1, 'year').endOf('year')] },
              ]}
            />
          </div>

          {/* Center Selection — hidden for managers (auto-set to their center) */}
          {user.role !== 'manager' && (
            <div>
              <label className="block text-sm font-medium text-gray-600 mb-1.5">Centers</label>
              <Select
                mode="multiple"
                value={selectedCenters}
                onChange={handleCenterChange}
                options={centerOptions}
                className="w-full"
                size="large"
                placeholder="Select centers"
                maxTagCount={3}
              />
            </div>
          )}

          {/* Status + Subject filters */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-600 mb-1.5">Status</label>
              <Select
                value={statusFilter}
                onChange={setStatusFilter}
                className="w-full"
                size="large"
                options={[
                  { value: 'all', label: 'All' },
                  { value: 'paid', label: 'Paid' },
                  { value: 'unpaid', label: 'Unpaid' },
                  { value: 'draft', label: 'Draft' },
                ]}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-600 mb-1.5">Subject</label>
              <Select
                value={subjectFilter}
                onChange={setSubjectFilter}
                className="w-full"
                size="large"
                options={[
                  { value: 'all', label: 'All' },
                  { value: 'course', label: 'Course' },
                  { value: 'materials', label: 'Materials' },
                  { value: 'gallery', label: 'Gallery' },
                  { value: 'registration', label: 'Registration' },
                ]}
              />
            </div>
          </div>

          {/* Export Format */}
          <div>
            <label className="block text-sm font-medium text-gray-600 mb-1.5">Format</label>
            <Select
              value={exportFormat}
              onChange={setExportFormat}
              className="w-64"
              size="large"
              options={[
                { value: 'xlsx', label: 'Excel (.xlsx)' },
                { value: 'csv', label: 'CSV (.csv)' },
              ]}
            />
          </div>

          {/* Field Selection */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm font-medium text-gray-600">
                Fields to Export
                <Tag className="ml-2" color="blue">{selectedFields.length} selected</Tag>
              </label>
              <div className="flex gap-2">
                <Button type="link" size="small" onClick={handleSelectAllFields}>Select All</Button>
                <Button type="link" size="small" onClick={handleDeselectAllFields}>Deselect All</Button>
              </div>
            </div>

            <div className="border border-gray-200 rounded-xl p-4 max-h-64 overflow-y-auto bg-gray-50/50">
              {FIELD_GROUPS.map(group => {
                const groupFields = EXPORT_FIELDS.filter(f => f.group === group);
                if (groupFields.length === 0) return null;

                return (
                  <div key={group} className="mb-3 last:mb-0">
                    <div className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1.5">{group}</div>
                    <div className="flex flex-wrap gap-x-1 gap-y-1">
                      {groupFields.map(field => (
                        <Checkbox
                          key={field.key}
                          checked={selectedFields.includes(field.key)}
                          onChange={() => handleFieldToggle(field.key)}
                          className="!ml-0"
                        >
                          <span className="text-sm">{field.label}</span>
                        </Checkbox>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </Modal>
    </>
  );
}

export default ExportBillsModal;
